### ISSUE TITLE
Article automatic curation is non deterministic

### ISSUE THREAD

**Issue by daniel-grumberg** [apple/swift-docc#291]
Articles get automatically curated in a non-deterministic order when building a docc archive without a top level extension file.

### Checklist
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected behavior
Curation order should be deterministic. When viewing a navigator built from such and archive I expect it to always have the same node ordering.

### Actual behavior
`FirstCurationRoot` and `SecondCurationRoot` get swapped non-deterministically.
[MultiCuratedSubtree.docc.zip](https://github.com/apple/swift-docc/files/8880683/MultiCuratedSubtree.docc.zip)

### Steps to Reproduce
Run `docc convert` on the provided catalogue

### Swift-DocC Version Information

**Swift-DocC version:** built from main
**Swift Compiler version:** N/A

**Comment by d-ronnqvist** [comment]
Since automatic curation for symbols is sorted alphabetically it would make sense to do the same for articles.

The article curation happens in [`autoCurateArticles(_:in:startingFrom:)`][1] and would probably be resolved by sorting `articleReferences`. 

It's always hard to test that something behaves deterministically but in this case I'd say that a test that expect the order of 3-4 automatically curated articles (just once) would be enough to feel safe that the order is stable.

[1]: https://github.com/apple/swift-docc/blob/main/Sources/SwiftDocC/Infrastructure/DocumentationContext.swift#L1853-L1899

**Comment by Kyle-Ye** [comment]
Can you still reproduce this issue on the main(https://github.com/apple/swift-docc/commit/f730fe5a86abe9ccad3cf64f34b29a22fffec52c) branch of swift-docc? @daniel-grumberg 

I could not reproduce it and the order is always "first and then second".

I add a assert expr and run the tests for 100 times and it still does not fail. 
```
let articleReferences = autoCuratedArticles.map(\.topicGraphNode.reference)
assert(articleReferences[0].pathComponents.last?.first == "F")
```

**Comment by Kyle-Ye** [comment]
This is confirmed to be fixed by #286.
