### ISSUE TITLE
Docc does not deal well with inline <!-- --> comments if they are first after the h1

### ISSUE THREAD

**Issue by ktoso** [apple/swift-docc#344]
### Description

Since we cannot add `@Comment` we need to use `<!-- -->` comments in docc markdown files.

Often the first few lines of a docc file under active development may be comment lines, like so:

```md
# ``Example``

<!-- FIXME: update docs when #23232323 is done -->

Provides a nice example...

## Hello world
```

---

The issue is that docc does not understand that the "_first line that is not empty_" actually is `Provides a nice example...` and thus the "subtitle" when referring to ``Example`` from other places, like a:

```

## Topics

### Articles

- <doc:Introduction>
- <doc:Example>
```

results in an empty "subtitle" for the Example:

![Screenshot 2022-07-25 at 18 41 03](https://user-images.githubusercontent.com/120979/180747590-14761cf6-d1d2-4d16-954b-b316166a419d.png)

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

But it should have been:

![Screenshot 2022-07-25 at 18 41 53](https://user-images.githubusercontent.com/120979/180747751-18fe5805-2ab2-424a-b94e-c14bea6c114e.png)

### Steps To Reproduce

Explained example situation above

### Swift-DocC Version Information

5.7

**Comment by Kyle-Ye** [comment]
According to the documentation 

https://github.com/apple/swift-docc/blob/10994beb45a91c8b1f2f231e575bd1fa62c2d2ba/Sources/SwiftDocC/Model/DocumentationMarkup.swift#L24-L25

It is the expected result as the first leading paragraph in the markup after the title is considered as an "HTMLBlock" type not a "Paragraph" type. So the parser assumes it does not have an abstract.

To workaround it temporary, we could use the following instead

```
# ``Example``

Provides a nice example...

<!-- FIXME: update docs when #23232323 is done -->

## Hello world
```

Or we could add a special check here as described in the issue "Description" (cc @franklinsch What do you think of it?)

**Comment by franklinsch** [comment]
Yes, I think when DocC tries to find the abstract of a page, it should skip comments, both `<!--` and `@Comment` styles. In general, you should be able to add comments anywhere in the Markdown without it affecting the output.

**Comment by Kyle-Ye** [comment]
> 



> Yes, I think when DocC tries to find the abstract of a page, it should skip comments, both `<!--` and `@Comment` styles. In general, you should be able to add comments anywhere in the Markdown without it affecting the output.

With that in mind, we should do the transform first (Drop all the `<!--` comments and `@Comment`). But this would involve a larger change/PR to fix it.

Should we use a small PR(#347) to temporarily fix it and file another issue to track it, or should we hold off until we can fix it globally?

**Comment by franklinsch** [comment]
Can you expand what you mean by "do the transform first"? It seems like it should be possible to extend your logic from #347 to skip `@Comment` as well?

**Comment by Kyle-Ye** [comment]
> Can you expand what you mean by "do the transform first"? It seems like it should be possible to extend your logic from #347 to skip `@Comment` as well?

I mean not only the "abstract" but the other logic should ignore the comments too. Currently, we only fix the comment issue in the "abstract" local scope.

**Comment by franklinsch** [comment]
Ah right, I think we should check if there are other places where we don't currently ignore comments, and see whether we should implement a more general filtering out of comments. For now, it would be good to fix the logic for abstracts.

**Comment by Kyle-Ye** [comment]
> ### Description
> Since we cannot add `@Comment` we need to use `<!-- -->` comments in docc markdown files.
> 

@ktoso What do you mean that "We cannot add `@Comment`"? It seems fine for me:

```
# ``Example``

@Comment {
    update docs when #23232323 is done
} 

Provides a nice example...

## Hello world
```

> It seems like it should be possible to extend your logic from https://github.com/apple/swift-docc/pull/347 to skip @Comment as well?

@franklinsch Actually the current logic already deal with `@Comment` and other block, see https://github.com/apple/swift-docc/blob/10994beb45a91c8b1f2f231e575bd1fa62c2d2ba/Sources/SwiftDocC/Model/DocumentationMarkup.swift#L144-L149

So it is already working fine with `@Comment`.

**Comment by ktoso** [comment]
> @ktoso What do you mean that "We cannot add @Comment"? It seems fine for me:

That's a separate bug where `@Comment { ... } ` does not work, which was tracked down separately and the workaround suggested was doing

```
@Comment { 
...
}
```

which indeed does work, but again, when I reported this issue here, I did not know that directives have parsing issues - so it seemed like we could not use @Comment at all, but we can -- just that we have to as multi-line.

**Comment by Kyle-Ye** [comment]
> That's a separate bug where `@Comment { ... } ` does not work, which was tracked down separately

Would you mind pointing out the issue number? I did not find it.

**Comment by ktoso** [comment]
Sorry seems there is no public issue about it but it right now - can we make one @franklinsch ?


In general the issue is that `@Comment { ... }` does not work at all, and it has to be 

```
@Comment {
...
}
```

**Comment by Kyle-Ye** [comment]
> Sorry seems there is no public issue about it but it right now - can we make one @franklinsch ?
> 
> In general the issue is that `@Comment { ... }` does not work at all, and it has to be
> 
> ```
> @Comment {
> ...
> }
> ```

Got it. Could you please sync the internal issue to Github issue so that we can track it more easily?

**Comment by ktoso** [comment]
I've asked @franklinsch to do so

**Comment by franklinsch** [comment]
Done, created #352 :)

**Comment by Kyle-Ye** [comment]
The Markdown syntax highlighting in Xcode will still have some unexpected behavior after a Html format comments - `<!-- -->`.

<img width="1457" alt="SCR-20230801-kejn" src="https://github.com/apple/swift-docc/assets/43724855/4287defd-6a1c-40b2-a1b6-38ce8afd2485">

Reported to Apple via FB11157755.

Since this is a bug on Xcode, I'm not going to create a issue here.

Just a information sync comment because it is related to this issue.
